name: Get Weather from Met Éireann

# This workflow is triggered daily at 20:00 UTC and can also be run manually using the "Run workflow" button.
# The workflow runs on the latest version of the Ubuntu operating system.
# The workflow checks out the repository, runs a script to get the weather data from Met Éireann, and commits and pushes the changes to the repository.

on:
  schedule:
    - cron: '0 20 * * *' # Runs daily at 20:00 UTC
  workflow_dispatch:

permissions:
  contents: write # Allows the workflow to push changes to the repository

jobs:
  run-weather-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository # Check out the repository so the script can access it
        uses: actions/checkout@v4

      - name: Run weather script # Run the weather script
        run: ./weather.sh

      - name: Commit and push changes # Commit and push the changes to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Scheduled weather update data'
          git push